#!/bin/bash

# Alex Hernandez and Matthew Fritz
# Bootstrapping A Laravel Project
# v1.1.0
# ===============================================================|

# GLOBAL VARS
NPM=$(which npm)
PHP=$(which php)
CURL=$(which curl)
BOWER=$(which bower)
COMPOSER=$(which composer)

# COMPOSER DEPENDENCIES
COMPOSER_DEPS="laravelcollective/html guzzlehttp/guzzle:~6.0 tiesa/ldap:dev-master csun-metalab/laravel-proxypass:^1.0 barryvdh/laravel-debugbar"

# APPLICATION EXIT CODES
E_NOERROR=0
E_DEPENDENCY=89

# CONSTANTS
PROJECT_DIR=$(pwd)

# Asks a Y/n question of the user and provides the result as a boolean.
#
# Example usage:
# retval=$(ask_question "Would you like to do something")
#
# The user then gets prompted with the question along with " (Y/n)? " appended.
#
# Input of y* or Y* results in true; input of n* or N* results in false.
function ask_question() {
  local _question="$1"

  while true; do
    read -p "$_question (Y/n)? " _answer
    # Set default for NULL or UNSET
    # http://www.network-theory.co.uk/docs/bashref/ShellParameterExpansion.html
    case ${_answer:-y} in
    [Yy]* )
      # Function called as $(ask_question "question") so return value can be
      # captured using command substitution
      _retval=true
      echo $_retval
      break
      ;;
    [Nn]* )
      # Function called as $(ask_question "question") so return value can be
      # captured using command substitution
      _retval=false
      echo $_retval
      break
      ;;
    * )
      printf "Please answer y or n. \n"
      ;;
    esac
  done
}

# LARAVEL BOOTSTRAP FUNCTIONS
function get_gist() {
  local _file="$1"
  local _uri="$2"

  ${CURL} -o "${_file}" "${_uri}"
  printf "\nYour ${_file} was updated successfully! \n"
}

function get_composer_package() {
  local _package="$1"

  printf "\nFetching '${_package}'... \n"
  ${COMPOSER} require ${_package}
  printf "Composer package '${_package}' was added successfully! \n"
}

# PACKAGE/DEPENDANCY AVAILABILITY CHECK
if [[ -z ${NPM} ]]; then
  echo "Oh no npm is missing!"
  exit $E_DEPENDENCY
elif [[ -z ${PHP} ]]; then
  echo "Oh no php is missing!"
  exit $E_DEPENDENCY
elif [[ -z ${CURL} ]]; then
  echo "Oh no curl is missing!"
  exit $E_DEPENDENCY
elif [[ -z ${BOWER} ]]; then
  echo "Oh no bower is missing!"
  exit $E_DEPENDENCY
elif [[ -z ${COMPOSER} ]]; then
  echo "Oh no composer is missing!"
  exit $E_DEPENDENCY
fi

printf "\n"

# CHECK FOR LARAVEL INSTALL
if [[ ! -f "${PROJECT_DIR}/artisan" ]]; then
  printf "Yo Man... Are you in the correct project directory? \nLaravel not found! \n\n"
  exit $E_DEPENDENCY
fi

# CREATE ENV + APP:KEY IF THE ENV FILE DOES NOT ALREADY EXIST
_env=$(ask_question "Do you wish to add a '.env' file")
if [[ ${_env} == true ]]; then
  if [[ -a ".env" ]]; then
    printf "\nYour env file already exists so this step will be skipped.\n"
  else
    cp .env.example .env
    printf "\nYour env was updated successfully! \n"
    ${PHP} artisan key:generate
  fi
fi

printf "\n"

# CREATE LARAVEL VIEW DIRECTORIES
_view_dirs=$(ask_question "Do you wish to create master & partial views")

if [[ ${_view_dirs} == true ]]; then
  mkdir "resources/views/pages"
  _page_template_file="landing.blade.php"
  _page_template_gist_uri="https://gist.githubusercontent.com/alexhernandez/486a758fdcac73e27687/raw/7049dbe66ac814038227cccc7f3d1b6f89c5a4a6/page.blade.php"

  pushd "resources/views/pages"
    get_gist "${_page_template_file}" "${_page_template_gist_uri}"
  popd

  mkdir -p "resources/views/layouts/partials"
  _master_template_file="master.blade.php"
  _master_template_gist_uri="https://gist.githubusercontent.com/alexhernandez/bc9f4a1994732e15df3d/raw/2d7d31fa89c3d231156e255d58feb05dc294f273/master.blade.php"

  pushd "resources/views/layouts"
    get_gist "${_master_template_file}" "${_master_template_gist_uri}"
  popd

  pushd "resources/views/layouts/partials"
    touch "nav.blade.php"
    touch "header.blade.php"
    touch "footer.blade.php"
    printf "\nYour partials were updated successfully! \n"
  popd
fi

printf "\n"

# ADD DEPENDENCIES
_dependencies=$(ask_question "Do you wish to add all project dependencies (bower,elixir,gulpfile,etc.)")

if [[ ${_dependencies} == true ]]; then
  # Create ".bowerrc" file
  _bower_file=".bowerrc"
  _bower_gist_uri="https://gist.githubusercontent.com/alexhernandez/c3b0d97538f5869d7f86/raw/8411a064facde1ea007585471f7683a0d546e2eb/.bowerrc"
  get_gist "${_bower_file}" "${_bower_gist_uri}"

  # Create "elixir.json" file
  _elixir_file="elixir.json"
  _elixir_gist_uri="https://gist.githubusercontent.com/alexhernandez/963c188f23e14e33929e/raw/a692c7ba6a911292d7d17875dde8c482b22c08a8/elixir.json"
  get_gist "${_elixir_file}" "${_elixir_gist_uri}"

  # Create "Gulpfile" file
  _gulp_file="gulpfile.js"
  _gulp_gist_uri="https://gist.githubusercontent.com/alexhernandez/42df05909d0dbb727ce2/raw/8d52543e942a6191b8e0b0953451e6a565c278fd/gulpfile.js"
  get_gist "${_gulp_file}" "${_gulp_gist_uri}"

  # Fetch and install all necessary Composer packages
  for _composer_package in ${COMPOSER_DEPS} ; do
    get_composer_package "${_composer_package}"
  done

  # Update config/app.php
  printf "\n"
  config_app_file="app.php"
  pushd "config"

    # Update "Providers" array
    sed -i .tmp "/'providers'/ a\\
    \\        Collective\\\Html\\\HtmlServiceProvider::class,\\
    \\        Barryvdh\\\Debugbar\\\ServiceProvider::class,\\
    \\        CSUNMetaLab\\\ProxyPass\\\Providers\\\ProxyPassServiceProvider::class,\\
    " ${config_app_file}

    # Update Aliases" array
    sed -i .tmp "/'aliases'/ a\\
    \\        'Form'      => Collective\\\Html\\\FormFacade::class,\\
    \\        'HTML'      => Collective\\\Html\\\HtmlFacade::class,\\
    \\        'Debugbar'  => Barryvdh\\\Debugbar\\\Facade::class,\\
    " ${config_app_file}

    # Remove .tmp files
    rm "${config_app_file}.tmp"
    printf "Your ${config_app_file} was updated successfully!"
  popd

  # Now that we have our service providers available, let's go ahead and
  # publish everything necessary from the vendor packages
  ${PHP} artisan vendor:publish

  # Add Bower to project
  # Create "bower.json" file
  printf "\nLets Initialize Bower... \n"
    _bower_file="bower.json"
    _bower_gist_uri="https://gist.githubusercontent.com/alexhernandez/bb21151902015a55d892/raw/2ce0791f347cb2c9ce3ca91304f1f322af248701/bower.json"
    get_gist "${_bower_file}" "${_bower_gist_uri}"

  # Install all Node Packages, --loglevel silent??? Look into this.
  printf "\nNow installing Node dependencies... \n Hang tight. This might take a bit... \n\n"
  ${NPM} install
fi

printf "\nYo Man... Your Laravel Application Has Been Successfully Bootstrapped! \n Wooooooooooot!!!"
echo ""
exit $E_NOERROR