#!/bin/bash

# Alex Hernandez
# Installing Sublime Text 3 Packages
# v1.0.0

# GLOBAL VARS
SUBL=$(which subl)
CURL=$(which curl)

# PACKAGE/DEPENDANCY AVAILABILITY CHECK
if [[ -z ${SUBL} ]]; then
  echo "Oh no Sublime Text is missing!"
  exit 2
elif [[ -z ${CURL} ]]; then
  echo "Oh no curl is missing!"
  exit 2
fi

while true; do
  printf "\n"
  read -p "Do you wish to add recommended Sublime Text 3 Packages? (Y/n) " answer
  case $answer in
  [Yy]* )
    pushd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User
      sublime_package_file="Package Control.sublime-settings"
      sublime_package_gist_uri="https://gist.githubusercontent.com/alexhernandez/07c91b2134d90815fdd8/raw/b17e78e86e221ab3cb7024caf363bdc3710b08a1/Package%2520Control.sublime-settings"
      ${CURL} -o "${sublime_package_file}" ${sublime_package_gist_uri}
    popd
    printf "\n"
    echo "Your Package Control.sublime-settings were updated successfully!"
    echo "Restart Sublime Text!"
    break
    ;;
  [Nn]* ) :
    break
    ;;
  * )
    echo "Please answer y or n."
    ;;
  esac
done
