#!/bin/bash

# Alex Hernandez
# Mac Configurations & App Management w/ Homebrew + Homebrew Cask
# v1.0.0

# Resource(s): http://brew.sh, http://caskroom.io
# Recommendation(s): View each repos USAGE.md for details
# ===============================================================|

# GLOBAL VARS
RUBY=$(which ruby)
BREW=$(which brew)
CURL=$(which curl)

# PACKAGE/DEPENDANCY AVAILABILITY CHECK
if [[ -z ${RUBY} ]]; then
  echo "Oh no ruby is missing!"
  exit 2
elif [[ -z ${BREW} ]]; then
  echo "Oh no brew is missing!"
  exit 2
elif [[ -z ${CURL} ]]; then
  echo "Oh no curl is missing!"
  exit 2
fi

# Homebrew Cask Extension Install
# Allows for application installation
while true; do
  read -p "Do you wish to install Homebrew Cask? (y/n) " answer
  case $answer in
    [Yy]* )
      ${BREW} install "caskroom/cask/brew-cask";
      break
      ;;
    [Nn]* ) :
      break
      ;;
    * )
      echo "Please answer y or n."
      ;;
  esac
done

# RECOMMENDED: Update .bash_profile to add app symbolic links in /Applications
# https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#options
while true; do
  read -p "Do you wish to add symbolic links to /Applications folder? (y/n) " answer
  case $answer in
    [Yy]* )
      echo "export HOMEBREW_CASK_OPTS='--appdir=/Applications'" >> ~/.bash_profile
      echo "Your ~/.bash_profile was updated successfully!"
      break
      ;;
    [Nn]* ) :
      break
      ;;
    * )
      echo "Please answer y or n."
      ;;
  esac
done

# Homebrew Bundle Tap
# Allows for Brewfile bulk installation
while true; do
  read -p "Do you wish to install Homebrew Bundle? (y/n) " answer
  case $answer in
    [Yy]* )
      ${BREW} tap "homebrew/bundle";
      break
      ;;
    [Nn]* ) :
      break
      ;;
    * )
      echo "Please answer y or n."
      ;;
  esac
done

# Install all binaries and applications listed in Brewfile
while true; do
  read -p "Do you wish to import your Brewfile Bundle? (y/n) " answer
  case $answer in
  [Yy]* )
    echo ${BREW} bundle install
    break
    ;;
  [Nn]* ) :
    break
    ;;
  * )
    echo "Please answer y or n."
    ;;
  esac
done
